### ISSUE TITLE
Assalomu aleykum Ilhomjon , headerni orqasini to'liq bo'yalishi kerak uning uchun bodydan max-widthni olib tashlang )

### ISSUE THREAD

**Issue by Azizbek-Kalandarov** [Ilkhomjon2604/Namanganliklar24-news#1]
![image](https://user-images.githubusercontent.com/74859443/134211548-46ba0d3b-7011-4b01-b302-e9b96d66ca95.png)

**Comment by Ilkhomjon2604** [comment]
changed . now there is no max width
