### ISSUE TITLE
Bu joyida time tagiga o'zgartirsangiz yaxshi bo'ladi span ichida time tagi bo'lishi kerak , rasmda ko'rishingiz mumkin qanaqa tartibda yozilishini  yil oy kun ketma-ketligida yozilad .) 

### ISSUE THREAD

**Issue by Azizbek-Kalandarov** [Ilkhomjon2604/Namanganliklar24-news#10]
![image](https://user-images.githubusercontent.com/74859443/134903514-38ce34e8-056f-4b5e-b8d9-9266ade69cec.png)
![image](https://user-images.githubusercontent.com/74859443/134903636-4d5911f4-1b38-488c-8edb-bd06cabae386.png)

**Comment by Ilkhomjon2604** [comment]
ozgartirildi
