### ISSUE TITLE
Ilhomjon bu yerda margin bo'lishi kerak edi sectionlar yopishib qolibdi margin bering sectionga 

### ISSUE THREAD

**Issue by Azizbek-Kalandarov** [Ilkhomjon2604/Namanganliklar24-news#7]
![image](https://user-images.githubusercontent.com/74859443/134863640-d4dc1cdd-1cc7-42b8-80e5-f1ee1933f4f8.png)

**Comment by Ilkhomjon2604** [comment]
technik xatolik yuz bergan shekil menda hammasi joyida
