### ISSUE TITLE
reklama qilingan bannerni rasmi nega yo'q img yo'llari xato berilmaganmi  ?  Shu rasmni qo'yish kerak element qolib ketishi kerak emas ) 

### ISSUE THREAD

**Issue by Azizbek-Kalandarov** [Ilkhomjon2604/Namanganliklar24-news#8]
![image](https://user-images.githubusercontent.com/74859443/134863775-f8cb389a-2114-4947-88a3-937a5d1d1052.png)
![image](https://user-images.githubusercontent.com/74859443/134863915-5b63848d-11c7-44f1-87b7-f9b0a7059f7a.png)

**Comment by Ilkhomjon2604** [comment]
texnik xatolik  menda korsatyapti va boshqa joydan ham kordm korsatyapti
