### ISSUE TITLE
Bu joyida <h3> emas a href link bo'lishi kerak chunki bu link bosilganda shu yangilik haqida to'liq ma'lumot bor linkga o'tkizib yuboradi  

### ISSUE THREAD

**Issue by Azizbek-Kalandarov** [Ilkhomjon2604/Namanganliklar24-news#9]
![image](https://user-images.githubusercontent.com/74859443/134864416-b49b16e2-3c05-4abc-8e92-bd50971a2fc4.png)

**Comment by Ilkhomjon2604** [comment]
h3 is changed to a link committe ostida tog'rilandi
